"""'test'

Revision ID: 4c5d1f09ce2d
Revises: 311464f7ec5b
Create Date: 2023-07-07 14:13:08.403350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5d1f09ce2d'
down_revision = '311464f7ec5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
